# Google Cloud Build Configuration
# Builds and deploys DocuMind API and Web to Cloud Run
#
# Required substitutions (set in Cloud Build trigger or via --substitutions):
# - _REGION: Cloud Run region (e.g., us-central1)
# - _API_SERVICE: API Cloud Run service name
# - _WEB_SERVICE: Web Cloud Run service name
# - _API_URL: Production API URL (e.g., https://api.documind.app)
#
# Required Secret Manager secrets:
# - DATABASE_URL
# - BETTER_AUTH_SECRET
# - GOOGLE_CLIENT_ID (optional)
# - GOOGLE_CLIENT_SECRET (optional)
# - STRIPE_SECRET_KEY (optional)
# - STRIPE_WEBHOOK_SECRET (optional)
# - RESEND_API_KEY (optional)

steps:
  # Step 1: Build and push API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:latest'
      - '-f'
      - 'apps/api/Dockerfile'
      - '.'
    id: 'build-api'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA'
    id: 'push-api'
    waitFor: ['build-api']

  # Step 2: Build and push Web image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:latest'
      - '-f'
      - 'apps/web/Dockerfile'
      - '--build-arg'
      - 'VITE_API_URL=${_API_URL}'
      - '.'
    id: 'build-web'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA'
    id: 'push-web'
    waitFor: ['build-web']

  # Step 3: Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_API_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,BETTER_AUTH_SECRET=BETTER_AUTH_SECRET:latest'
      - '--update-secrets'
      - 'GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,RESEND_API_KEY=RESEND_API_KEY:latest'
    id: 'deploy-api'
    waitFor: ['push-api']

  # Step 4: Deploy Web to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_WEB_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '80'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--allow-unauthenticated'
    id: 'deploy-web'
    waitFor: ['push-web']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:latest'
  - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:latest'

# Build timeout (15 minutes)
timeout: '900s'

# Substitutions with defaults
substitutions:
  _REGION: 'us-central1'
  _API_SERVICE: 'documind-api'
  _WEB_SERVICE: 'documind-web'
  _API_URL: 'https://api.documind.app'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
